
# apt install docker.io
# apt-get install docker-compose; apt install python3-pip
# identity.public and identity.secret from /var/lib/zerotier-one
# zerotier-idtool generate  identity.secret identity.public 
# zerotier-cli peers; zerotier-cli listnetworks
services:
  zerotier:
    #image: registry.cn-chengdu.aliyuncs.com/tickg/zerotier-zerotier:1.14.0
    #image: zerotier/zerotier:1.14.0
    image: zerotier/zerotier:latest
    network_mode: host
    container_name: zerotier
    restart: unless-stopped
    #env_file:
    #  - settings.env
    environment:
      TEST: ${ZEROTIER_API_SECRET}
       # /var/lib/zerotier-one/authtoken.secret
      ZEROTIER_API_SECRET: ${ZEROTIER_API_SECRET}
       # /var/lib/zerotier-one/identity.public
      ZEROTIER_IDENTITY_PUBLIC: ${ZEROTIER_IDENTITY_PUBLIC} 
       # /var/lib/zerotier-one/identity.secret
      ZEROTIER_IDENTITY_SECRET: ${ZEROTIER_IDENTITY_SECRET} 
    command: [ '${NETWORK_ID}' ]
    volumes:
        # out:in
      - ./data:/data
      #- ./data/identity.public:/var/lib/zerotier-one/identity.public
      #- ./data/identity.secret:/var/lib/zerotier-one/identity.secret
      
    cap_add: 
      - ALL
    devices:
      - /dev/net/tun:/dev/net/tun
    #ports:
      # out:in 
      #- 9993:9993
      